apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: new-virtualservice
spec:
  hosts:
  - '*'
  gateways:
  - demo-gateway
  http:
  - match:
    - uri:
        prefix: /api/v1
    route:
    - destination:
        host: newapp.default.svc.cluster.local
        port:
          number: 8080
